mutation CreateUser ($username: String!,
    $password: String!, $firstname: String, $lastname: String,
    $email: String!, $preferences: [ID]!
    ) {
        signup(
            data: {
                username: $username
                password: $password
                firstname: $firstname
                lastname: $lastname
                email: $email,
                preferences: { connect: $preferences}
            }
        ) { id }
    }