query Progression($userID: ID!, $url: String!) {
    progressions(
        where: {
            user: {
                id: $userID
            }
            manga: {
                url: $url
            }
        }
    ) {
        id
        avancement
    }
}
