query SeasonProgression($userID: ID!, $progressURL: String!, $type: String!) {
    seasonProgression(data: {
        type: $type
        userID: $userID
        progressURL: $progressURL
    }){
        progression
    }
}