mutation UpsertMangaReading ($avancement: Float!, $id: ID!) {
    updateProgression (
        where: {
            id: $id
        }
        data: {
            avancement: $avancement
        }
    ){ id }
}