query UsernameVerif($username: String $email: String) {
    username: usersConnection(where: { username: $username }) {
        aggregate {
            count
        }
    }

    email: usersConnection(where: { email: $email }) {
        aggregate {
            count
        }
    }
}